name: Create release

on:
  push:
    tags:
      - "v-*"

jobs:
  createTags:
    runs-on: ubuntu-latest
    - steps:
       - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 确保获取所有历史以便正确生成标签

       - name: Check tag format
          run: |
            git checkout master
            TAG_NAME=${GITHUB_REF#refs/tags/}
            if [[ $TAG_NAME =~ ^v-[0-9]{8}-[0-9]+$ ]]; then
              echo "Tag format is correct. ✅"
              npm version patch -m "Upgrade to %s for reasons [skip ci]"
              git push "https://github.com/Junlin-Robin/test-action.git"
            else
              echo "Tag format is incorrect. ❌"
              exit 1
            fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: name: Read Markdown file
        id: readme
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          FILE_NAME="${TAG_NAME}.md"
          content=$(cat src/tag-info/$FILE_NAME)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=content::$content"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.readme.outputs.content }}
          draft: false
          prerelease: false